// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfrNmukxRp7DLYEPXNuIVSLAPN8dbXHlY',
    appId: '1:371206347943:web:0c2ce2742ab7fdab670f82',
    messagingSenderId: '371206347943',
    projectId: 'circle-app-d9f18',
    authDomain: 'circle-app-d9f18.firebaseapp.com',
    storageBucket: 'circle-app-d9f18.firebasestorage.app',
    measurementId: 'G-21F24Q2C06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbEkCoYZQnGAjzQUTh_uRzXuasyt8DyvU',
    appId: '1:371206347943:android:7ac0a7749b57f737670f82',
    messagingSenderId: '371206347943',
    projectId: 'circle-app-d9f18',
    storageBucket: 'circle-app-d9f18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwgVqhHwGf103Z4HuJ7aocoywXupJ52R0',
    appId: '1:371206347943:ios:74f4bb0a995fb82a670f82',
    messagingSenderId: '371206347943',
    projectId: 'circle-app-d9f18',
    storageBucket: 'circle-app-d9f18.firebasestorage.app',
    iosClientId: '371206347943-o8bn7mrh5i9c7a4rcp92er3u1d294bh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.circleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwgVqhHwGf103Z4HuJ7aocoywXupJ52R0',
    appId: '1:371206347943:ios:74f4bb0a995fb82a670f82',
    messagingSenderId: '371206347943',
    projectId: 'circle-app-d9f18',
    storageBucket: 'circle-app-d9f18.firebasestorage.app',
    iosClientId: '371206347943-o8bn7mrh5i9c7a4rcp92er3u1d294bh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.circleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfrNmukxRp7DLYEPXNuIVSLAPN8dbXHlY',
    appId: '1:371206347943:web:9f93b7569b394847670f82',
    messagingSenderId: '371206347943',
    projectId: 'circle-app-d9f18',
    authDomain: 'circle-app-d9f18.firebaseapp.com',
    storageBucket: 'circle-app-d9f18.firebasestorage.app',
    measurementId: 'G-6D42RLY67G',
  );
}
